steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/top-heroes-companion", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/top-heroes-companion"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "top-heroes-companion"
      - "--image=gcr.io/$PROJECT_ID/top-heroes-companion"
      - "--platform=managed"
      - "--region=us-east1"
      - "--port=8080"

options:
  logging: CLOUD_LOGGING_ONLY
